FROM public.ecr.aws/lambda/python:3.10 AS builder

RUN yum update -y && \
    yum install -y gcc-c++ && \
    yum clean all

RUN pip install --upgrade pip

COPY requirements.txt .

RUN pip install --no-cache-dir "numpy==1.26.4" -t ./python

RUN pip install --no-cache-dir -r requirements.txt -t ./python

FROM public.ecr.aws/lambda/python:3.10

COPY --from=builder /var/task/python /var/lang/lib/python3.10/site-packages/

COPY handler.py .

CMD [ "handler.lambda_handler" ]